spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/testorder}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:bavui4444}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # update | validate | create | create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8082
  servlet:
    context-path: /testorder

jwt:
  secret: "my-super-ultra-promax-vip-pro-password-32-bytes-long"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

app:
  encryption:
    secret-key: mySecretKey12345