# Patient Service CI/CD Pipeline
.patient-service-changes: &patient-service-changes
  rules:
    # - if: $CI_PIPELINE_SOURCE == "merge_request_event" && ($CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "main")
    #   changes:
    #     - patient-service/pom.xml
    #     - patient-service/src/**/*
    #     - patient-service/.gitlab-ci.yml
    #     - patient-service/Dockerfile

    #   when: always
    - if: $CI_COMMIT_BRANCH == "main" # || $CI_COMMIT_BRANCH == "develop"
      changes:
        - patient-service/pom.xml
        - patient-service/src/**/*
        - patient-service/.gitlab-ci.yml
        - patient-service/Dockerfile
      when: always
    - when: never

# Build and Package Patient Service
build-and-package-patient-service:
  <<: *patient-service-changes
  stage: build
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  variables:
    DOCKER_TLS_CERTDIR: ""
    DOCKER_HOST: tcp://docker:2375
  before_script:
    - cd patient-service
    - docker info
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script: |
    echo "Building and pushing Patient Service Docker image..."
    export DATETIME=$(date +%Y%m%d-%H%M%S)
    echo "Building with timestamp - $DATETIME"
    echo "Building complete Docker image using your Dockerfile"
    docker build -t $REGISTRY/patient-service:$DATETIME .
    docker build -t $REGISTRY/patient-service:latest .
    echo "Pushing Docker images..."
    docker push $REGISTRY/patient-service:$DATETIME
    docker push $REGISTRY/patient-service:latest
    echo "Patient Service Docker image built and pushed successfully"
    echo "Available images:"
    echo "  - $REGISTRY/patient-service:$DATETIME"
    echo "  - $REGISTRY/patient-service:latest"
  cache:
    key: patient-docker-$CI_COMMIT_REF_SLUG
    paths:
      - patient-service/.m2/repository/

# Test Patient Service
# test-patient-service:
#   <<: *patient-service-changes
#   stage: test
#   image: maven:3.9.4-eclipse-temurin-21
#   services:
#     - postgres:17-alpine
#   variables:
#     POSTGRES_DB: patient_test
#     POSTGRES_USER: postgres
#     POSTGRES_PASSWORD: test
#     POSTGRES_HOST_AUTH_METHOD: trust
#     SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/patient_test
#     SPRING_DATASOURCE_USERNAME: postgres
#     SPRING_DATASOURCE_PASSWORD: test
#   before_script:
#     - cd patient-service
#   script:
#     - echo "Running Patient Service tests..."
#     - mvn $MAVEN_CLI_OPTS test
#   artifacts:
#     reports:
#       junit: patient-service/target/surefire-reports/TEST-*.xml
#       coverage_report:
#         coverage_format: jacoco
#         path: patient-service/target/site/jacoco/jacoco.xml
#     paths:
#       - patient-service/target/surefire-reports/
#       - patient-service/target/site/jacoco/
#     expire_in: 1 week
#   coverage: "/Total.*?([0-9]{1,3})%/"
#   dependencies:
#     - build-patient-service
#   when: manual # Make tests optional until they are written
#   allow_failure: true # Don't block pipeline if tests fail
