spring:
  application:
    name: patient-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/patient-db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:trquth1209}

  grpc:
    server:
      port: 9091

  rabbitmq:
    host: ${RABBITMQ_HOST:host.docker.internal}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  data:
    mongodb:
      uri: ${MONGO_URI_PATIENT:mongodb://admin:bavui4444@localhost:27017}
      database: ${MONGO_DATABASE_NAME:microservices}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  servlet:
    context-path: /patient

jwt:
  secret: "my-super-ultra-promax-vip-pro-password-32-bytes-long"

logging:
  level:
    org.springframework.grpc: DEBUG

app:
  encryption:
    secret-key: mySecretKey12345
