spring:
  application:
    name: patient-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: patient_schema

  datasource:
    url: jdbc:postgresql://localhost:5432/patient-db
    username: postgres
    password: trquth1209

  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest

  data:
    mongodb:
      uri: ${MONGO_URI_PATIENT}
      database: ${MONGO_DATABASE_NAME}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

server:
  port: 8081
  servlet:
    context-path: /patient
jwt:
  secret: "my-super-ultra-promax-vip-pro-password-32-bytes-long"

  rabbitmq:
    host: host.docker.internal
    port: 5672
    username: guest
    password: guest
