spring:
  application:
    name: patient-service

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  datasource:
    url: jdbc:postgresql://localhost:5432/patient
    username: postgres
    password: bavui4444

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

server:
  port: 8081
  servlet:
    context-path: /patient
jwt:
  secret: "my-super-ultra-promax-vip-pro-password-32-bytes-long"
