spring:
  application:
    name: iam-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false

    mail:
      host: smtp.gmail.com
      port: 587
      username: ${SPRING_MAIL_USERNAME}
      password: ${SPRING_MAIL_PASSWORD}
      protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
      default-encoding: UTF-8

server:
  port: 8080
  servlet:
    context-path: /iam

management:
  endpoints:
    web:
      exposure:
        include: ${MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE:health,info,metrics}
  endpoint:
    health:
      show-details: ${MANAGEMENT_ENDPOINT_HEALTH_SHOW_DETAILS:when-authorized}
  server:
    port: 8080

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT:WARN}
    org.springframework.security: WARN
    org.hibernate.SQL: WARN
